version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "jaredhendrickson13"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "jaredhendrickson13"
