#!/usr/bin/python3
# ----------------------------------------------------------------------------------------------------------------
# Author: Jared Hendrickson
# Copyright 2020 - Jared Hendrickson
# ----------------------------------------------------------------------------------------------------------------

import argparse
import pfvshell

class PFCLI:
    def __init__(self):
        parser = argparse.ArgumentParser(description='Run shell commands on pfSense without SSH')
        parser.prog = "pfsense-vshell"
        parser.add_argument(
            '--username', "-u",
            dest="username",
            required=False,
            help='Set the username to use when authenticating',
        )
        parser.add_argument(
            '--username', "-u",
            dest="username",
            required=False,
            help='Set the username to use when authenticating',
        )
        parser.add_argument(
            '--password', "-p",
            dest="password",
            required=False,
            help='Set the password to use when authenticating',
        )

        self.args = parser.parse_args()

PFCLI()